service: shl-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'


plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 4000